This notebook can be used to map the dataset as taken from the israeli website and map it to an english translation.

In [1]:
import pandas as pd

In [2]:
covid_0220_df = pd.read_csv('./data/corona_tested_individuals_ver_00220.csv')
covid_0220_df

C:\Users\ahegarty\.conda\envs\DataScienceMsc\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (7,8) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,test_date,cough,fever,sore_throat,shortness_of_breath,head_ache,corona_result,age_60_and_above,gender,test_indication
0,2022-01-30,0,0,0,0,0,חיובי,No,נקבה,Other
1,2022-01-30,0,0,0,0,0,חיובי,No,נקבה,Other
2,2022-01-30,0,0,0,0,0,חיובי,No,זכר,Other
3,2022-01-30,0,0,0,0,0,חיובי,No,נקבה,Other
4,2022-01-30,0,0,0,0,0,חיובי,No,נקבה,Other
...,...,...,...,...,...,...,...,...,...,...
8890296,2020-03-11,0,0,0,0,0,שלילי,NaN,זכר,Other
8890297,2020-03-11,0,0,0,0,0,שלילי,NaN,נקבה,Other
8890298,2020-03-11,0,0,0,0,0,שלילי,NaN,נקבה,Other
8890299,2020-03-11,0,0,0,0,0,שלילי,NaN,זכר,Other
8890300,2020-03-11,0,0,0,0,1,שלילי,NaN,זכר,Other

In [3]:
corona_result_dict = {
    'שלילי':'negative',
    'חיובי':'positive',
    'אחר':'other'
}

gender_dict = {
    'נקבה':'female',
    'זכר':'male'
}

In [4]:
covid_0220_df['gender'] = covid_0220_df['gender'].map(gender_dict)
covid_0220_df['corona_result'] = covid_0220_df['corona_result'].map(corona_result_dict)

In [5]:
covid_0220_df.to_csv('./data/corona_tested_individuals_ver_00220.english.csv', index = False)

In [ ]:
# Lets see how the data is changing over time

# First in terms of number of cases both negative and positive over time.


grouped_by_date_count = covid_0220_df.groupby(['test_date', 'corona_result']).count()
grouped_by_date_mean = covid_0220_df.groupby(['test_date', 'corona_result']).mean()